# Generated by Django 4.2.23 on 2025-08-31 15:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSobres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sobre_n', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Número de sobre')),
                ('hermano', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Asignación de sobres',
                'verbose_name_plural': 'Asignaciones de sobres',
                'ordering': ['sobre_n'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('ingreso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('egreso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('saldo', models.DecimalField(decimal_places=2, help_text='Saldo luego del movimiento', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('-9999999999.99'))])),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Compromisos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Concepto')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Descripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Descripción')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntregadoA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Entregado a')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado de Moneda',
                'verbose_name_plural': 'Estados de Moneda',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoVencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado de Vencimiento',
                'verbose_name_plural': 'Estados de Vencimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RetiroBuzon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Retiro buzón')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Situación')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(help_text='Fecha de registro o recepción')),
                ('fecha_vencimiento', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('nota', models.TextField(blank=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='inventario.concepto')),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='inventario.descripcion')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='inventario.estadovencimiento')),
                ('situacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vencimientos', to='inventario.situacion')),
            ],
            options={
                'ordering': ['-fecha_vencimiento', 'concepto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='OfrendaDonacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('concepto', models.CharField(blank=True, max_length=200)),
                ('entregado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofrendas', to='inventario.entregadoa')),
                ('retiro_buzon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ofrendas', to='inventario.retirobuzon')),
            ],
            options={
                'verbose_name': 'Ofrenda / Donación',
                'verbose_name_plural': 'Ofrendas y Donaciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('ingreso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('egreso', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ganancia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Interés')),
                ('saldo', models.DecimalField(decimal_places=2, help_text='Saldo (incluye intereses por mes/meses)', max_digits=14)),
            ],
            options={
                'verbose_name': 'Movimiento MP',
                'verbose_name_plural': 'Movimientos MP',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha'], name='inventario__fecha_64652d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonedaExtranjera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text='Código ISO (USD, EUR, etc.)', max_length=3, validators=[django.core.validators.RegexValidator(message='Usar código ISO 4217 en mayúsculas (p.ej., USD).', regex='^[A-Z]{3}$')])),
                ('fecha', models.DateField()),
                ('ingreso', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ingreso (USD)')),
                ('compra_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Compra (USD)')),
                ('compra_ars', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Compra (ARS)')),
                ('egreso_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Egreso (USD)')),
                ('usd_hoy', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cotización USD hoy')),
                ('venta_ars', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Venta (ARS)')),
                ('saldo_ars', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Saldo (ARS)')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_moneda', to='inventario.estadomoneda')),
            ],
            options={
                'verbose_name': 'Moneda extranjera',
                'verbose_name_plural': 'Moneda extranjera',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuotaInac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hermano', models.CharField(max_length=120)),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(3000)], verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Cuota INAC',
                'verbose_name_plural': 'Cuotas INAC',
                'ordering': ['-anio', '-mes', 'hermano'],
                'indexes': [models.Index(fields=['anio', 'mes'], name='inventario__anio_6ae78e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cuotainac',
            constraint=models.UniqueConstraint(fields=('hermano', 'mes', 'anio'), name='unique_cuota_por_mes_anio_hermano'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='inventario.asignacionsobres', verbose_name='Asignación (Sobre/Hermano)'),
        ),
        migrations.AddIndex(
            model_name='caja',
            index=models.Index(fields=['fecha'], name='inventario__fecha_6eeafe_idx'),
        ),
        migrations.AddIndex(
            model_name='vencimiento',
            index=models.Index(fields=['fecha_vencimiento'], name='inventario__fecha_v_879a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='vencimiento',
            index=models.Index(fields=['concepto'], name='inventario__concept_d211f9_idx'),
        ),
        migrations.AddIndex(
            model_name='vencimiento',
            index=models.Index(fields=['estado'], name='inventario__estado__2f0eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='ofrendadonacion',
            index=models.Index(fields=['fecha'], name='inventario__fecha_036920_idx'),
        ),
        migrations.AddIndex(
            model_name='monedaextranjera',
            index=models.Index(fields=['fecha'], name='inventario__fecha_67146f_idx'),
        ),
        migrations.AddIndex(
            model_name='monedaextranjera',
            index=models.Index(fields=['codigo'], name='inventario__codigo_8db8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='compromiso',
            index=models.Index(fields=['fecha'], name='inventario__fecha_ee5153_idx'),
        ),
        migrations.AddIndex(
            model_name='compromiso',
            index=models.Index(fields=['asignacion'], name='inventario__asignac_f4c575_idx'),
        ),
    ]
