# Generated by Django 4.2.23 on 2025-09-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_seed_catalogos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entregadoa',
            options={'ordering': ['nombre'], 'verbose_name': 'Entregado A', 'verbose_name_plural': 'Entregados A'},
        ),
        migrations.AlterModelOptions(
            name='retirobuzon',
            options={'ordering': ['nombre'], 'verbose_name': 'Retiro Buzón', 'verbose_name_plural': 'Retiros Buzón'},
        ),
        migrations.AlterModelOptions(
            name='situacion',
            options={'ordering': ['nombre'], 'verbose_name': 'Situación', 'verbose_name_plural': 'Situaciones'},
        ),
    ]
