"""
Django settings for lector project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from .env import env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)
ALLOWED_HOSTS = [".azurewebsites.net", "127.0.0.1", "localhost", ".sinaptic.site", "192.168.1.53", ".onrender.com"]
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=ALLOWED_HOSTS)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CSRF_TRUSTED_ORIGINS = [
    "https://hftgestionproductos-bsachxb2h0edfnhs.canadacentral-01.azurewebsites.net",
    "https://hftecno.sinaptic.site",
    "http://192.168.1.53:8000",
    "https://inac-finanzas.onrender.com/",
]

# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inventario',
]

# Para usar templates de Unfold
UNFOLD = {
    "SITE_TITLE": "Lector OC",
    "SITE_HEADER": "Sinaptic",
    "SITE_LOGO": {
        "light": "/static/images/inac-logo.png",  # light mode
        "dark": "/static/images/inac-logo-dark.png",  # dark mode
    },
    # "SITE_FAVICONS": [
    #     {
    #         "rel": "icon",
    #         "sizes": "32x32",
    #         "type": "image/x-icon",
    #         "href": "/static/images/favicon-32x32.ico",
    #     },
    #     {
    #         "rel": "icon",
    #         "sizes": "128x128",
    #         "type": "image/x-icon",
    #         "href": "/static/images/favicon-128x128.ico",
    #     },
    #     {
    #         "rel": "icon",
    #         "sizes": "256x256",
    #         "type": "image/x-icon",
    #         "href": "/static/images/favicon-256x256.ico",
    #     },
    # ],
    "COLORS": {
        "primary": {
            "50":  "235, 246, 255",
            "100": "210, 234, 254",
            "200": "178, 219, 252",
            "300": "133, 196, 250",
            "400": "90, 171, 243",
            "500": "37, 143, 235",   # #258FEB tono principal
            "600": "28, 115, 202",
            "700": "23, 92, 163",
            "800": "19, 72, 127",
            "900": "15, 54, 95",
            "950": "10, 36, 64",
        },
    },
    "SIDEBAR": {
        "show_search": False,  # Search in applications and models names
        "command_search": False,  # Replace the sidebar search with the command search
        "show_all_applications": False,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": _("Gestión"),
                "collapsible": True, # Collapsible group of links
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",  # Supported icon set: https://fonts.google.com/icons
                        # "link": reverse_lazy("admin:index"),
                        "link": "/admin/",
                        # "badge": "sample_app.badge_callback",
                        # "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("Caja"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventario_caja_changelist"),
                    },
                    {
                        "title": _("Movimientos MP"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventario_mp_changelist"),
                    },
                    {
                        "title": _("Vencimiento"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventario_vencimiento_changelist"),
                    },
                    {
                        "title": _("Moneda extranjera"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventario_monedaextranjera_changelist"),
                    },
                    {
                        "title": _("Compromisos"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventario_compromiso_changelist"),
                    },
                    {
                        "title": _("Ofrendas y Donaciones"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventario_ofrendadonacion_changelist"),
                    },
                    {
                        "title": _("Asignacion de Sobres"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventario_asignacionsobres_changelist"),
                    },
                    {
                        "title": _("Cuotas INAC"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:inventario_cuotainac_changelist"),
                    },
                ],
            },
            {
                "title": _("Configuración"),
                "separator": True, # Top border
                "collapsible": True, # Collapsible group of links
                "items": [
                    {
                        "title": _("Estados Vencimiento"),
                        "icon": "people",
                        "link": reverse_lazy("admin:inventario_estadovencimiento_changelist"),
                    },
                    {
                        "title": _("Concepto"),
                        "icon": "people",
                        "link": reverse_lazy("admin:inventario_concepto_changelist"),
                    },
                    {
                        "title": _("Situación"),
                        "icon": "people",
                        "link": reverse_lazy("admin:inventario_situacion_changelist"),
                    },
                    {
                        "title": _("Descripción"),
                        "icon": "people",
                        "link": reverse_lazy("admin:inventario_descripcion_changelist"),
                    },
                    {
                        "title": _("Estado Moneda"),
                        "icon": "people",
                        "link": reverse_lazy("admin:inventario_estadomoneda_changelist"),
                    },
                    {
                        "title": _("Retiro Buzón"),
                        "icon": "people",
                        "link": reverse_lazy("admin:inventario_retirobuzon_changelist"),
                    },
                    {
                        "title": _("Entregado A"),
                        "icon": "people",
                        "link": reverse_lazy("admin:inventario_entregadoa_changelist"),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lector.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# PARA USAR SQLITE EN LOCAL:
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

USE_AZURE_DB = env.bool("USE_AZURE_DB", default=False)

if USE_AZURE_DB:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env("AZURE_MYSQL_NAME"),
            "USER": env("AZURE_MYSQL_USER"),
            "PASSWORD": "$QlBnD0W$tK03Hq4",
            "HOST": env("AZURE_MYSQL_HOST"),
            "PORT": env("AZURE_MYSQL_PORT", default="3306"),
            "OPTIONS": {
                "ssl": {
                    "ca": os.path.join(BASE_DIR, "certs", "DigiCertGlobalRootCA.crt.pem"),
                },
                "ssl_mode": "VERIFY_IDENTITY"
            },
        }
    }
else:
    SQLITE_PATH = Path("/home/site/wwwroot/db.sqlite3")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

LANGUAGE_CODE = 'es'

# python manage.py compilemessages -l es

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Carpeta para collectstatic en producción
STATIC_ROOT = BASE_DIR / "staticfiles"

# Carpetas donde buscás static files en desarrollo
STATICFILES_DIRS = [BASE_DIR / "static"]

# Whitenoise
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
